---
title: "les 5: vooruitkijken" 
subtitle: "HU OSIRIS: tlsc-dsfb26v-20_workflows"
author: "Alyanne de Haan, Chris van Oevelen"
date: "jaar 2021/2022"
output: 
  ioslides_presentation:
     widescreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## dagplanning
 - 9:00: planning en uitleg open ruimte en portfolio
 - 9:15 bij iedereen langs wat ze gaan doen voor de open ruimte. 
 - 10:30 koffie
 - 10:45 sources-opdracht
 - 11:45 lunch
 - 12:30 hoe citeren-opdracht

## jaar 1 + 2

 - basis statistiek, wiskunde, excel
 - basis bioinformatica
 - heel veel biologie / life sciences!

## DSFB1+2 

In DSFB1 + 2

 - basis GNU / linux / bash, toepassing op bioinformatica
 - basis dataverwerking in R
 - bioinformatica in R
 - toepassen skills in projecticum
 - workflows:
    - open science
    - version control
    - reproducible workflow (RMarkdown)
    - SQL

## DSFB1+2

Dus:

 - 1 taal aardig wat + intro in 2 andere
 - toepassing op bioinformatica
 - ondersteunende skills

## Ben ik nou een bioinformaticus?

Weet je niche

 - bio(medisch) analist met een bioinformatica / data science "minor"
 - dat is je selling point, gebruik dat!
 - groeiende vraag in het werkveld
 - geen ICT-ers, geen bioinformatici (kan wel, moet je verder studeren)

## nu in DSFB2

Start gemaakt met projecticum

Op zoek naar stageplaatsen

Beetje beeld van de mogelijkheden


## 3 vragen

 - waar wil ik naartoe?
 - hoe doe ik het nu?
 - wat is de volgende stap?

## les 7 (9 mei)

Plan open ruimte af:

 - waar wil je naartoe?
 - welke stap is dan na DSFB2?
 - plan van aanpak om daar ca 4 dagen aan te werken dit blok

## les 8 (16 mei)

presentaties portfolio (5-10 minuten per persoon)

 - wat heb je af
 - opmaak
 - wat komt er nog
 - toelichting open ruimte (groot deel)

verzamel en verwerk de feedback! We doen dit niet voor niets 3 weken voor de deadline.

## voorbeelden

 - Snakemake uitzoeken
 - start maken met python
 - meer NGS workflows leren
 - goed worden in SQL
 - shiny leren
 - labjournaals automatiseren
 - toepassingen R in microbiologie uitzoeken

## voorbeelden

 - pca
 - proteomics
 - chemoinformatic
 - start maken met machine learning
 - image processing data anlyse leren
 - bayesian statistics
 - misschien wil je een premaster of hbo master doen met requirements die je nog niet hebt?

## uren: 140 (5 EC)
 
 - 5*9=45 uur lessen
 - zelf bijwerken / voorbereiden: 3*9 = 27 uur
 - portfolio afmaken: 32 uur
 
 
 --> ca 32 uur (= zeg 4 dagen) de tijd!
 om een start te maken.(+ 4 uur voor het rapporteren/presenteren)

## eisen:

 - moet over biologie gaan
 - moet over data science / bioinformatica gaan
 - leren haken moet een andere keer
 - moet in je portfolio

## Vandaag

 - lekker lesje syntax
 - plaatjes, cross references & references 
 - opmaak voor je portfolio (maak er wat van)
 - dagopdracht: inleiding projecticum + references

## dagplanning
 - 9:00: planning en uitleg open ruimte en portfolio
 - 9:15 bij iedereen langs wat ze gaan doen voor de open ruimte. 
 - 10:30 koffie
 - 10:45 waarom bronnen gebruiken -opdracht
 - 11:45 lunch
 - 12:30 hoe bronnen gebruiken -opdracht
