# Prerequisites {.unnumbered #preparingforthecourse}

<!-- unnumbered + label should work but it doesn't -->
<!-- https://bookdown.org/yihui/rmarkdown-cookbook/unnumbered-sections.html -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Software {#softwarelist}
This course assumes you have a working installation and administrator access to the following software - Below we assume you have the ability to install the software on a local laptop. Please contact the teachers if you do not have this possibility. 

 1. [Docker Desktop](https://www.docker.com/get-started)
 1. [Visual Studio Code - Microsoft](https://code.visualstudio.com/)
 1. [Visual Studio Code Docker plugin](https://code.visualstudio.com/)
 1. [R - at least Version 4.0](https://cran.r-project.org/)
 1. [RStudio IDE](https://rstudio.com/products/rstudio/download/)
 1. [Git for Windows](https://git-scm.com/download/win)
 1. [DBeaver](https://dbeaver.io/)
 1. [CyberDuck](https://cyberduck.io/)
 1. [Microsoft Teams](https://www.microsoft.com/nl-nl/microsoft-teams/group-chat-software)

For some exercises and assignment you need an Server account. You you can use your RStudio Server account from the previous DSFB2 ("DAUR2") course.

## Additional 'things'

Some additional things you need to take into account or that you will need for this course:

 - When installing the software, make sure you install the software in the order indicated above
 - Next to this software we assume you also have an account set up in Github.com. You will need this to setup your portfolio, which will be the end-product for this course and which will be needed for passing the exam
 - We will use HU CANVAS to communicate with you and guide you through the exercises and assignments. The content of the course (reader, code, examples etc.)
 - During the course we will monitor you active participation in group or session chats, participation in the Q&A platform and your commits on github. We expect an active contribution and will take your activity into account when determining your score for the course. 

## Online Sessions
The online sessions require you to have an internet connection and an updated version of Microsoft Teams and sufficient bandwith to use audio and video during the sessions.

## Seeking interaction and help
During this course we really invite you to seek interaction on the course contents, the exercises and assignments with fellow course participants and the instructors. In order to facilitate this we will have a specific Q&A platform ready for you. The details will be made known on CANVAS.

## Exam
The credits for this course can be earned by handing in the final portfolio. The details are described here \@ref(portfolioexam). In short: You will have to publish a bookdown project to github pages in your github account. This page will function as a portfolio where you will post all the assignments and output products of the course. Only the lecturers of the course will have access to your portfolio products. Bookdown and github will be covered within this course.


## Exercise and assignment directives
Within the lesson you will encounter a number of exercises. 

Please answer all the assignments and exercises in an RMarkdown document. You learned how to make one in DAUR1. Save it somewhere in your course project. 

At the end of every lesson (and sometimes in the middle), there is a larger _portfolio assignment_. You will work on this assignment for the rest of the day, after finishing the smaller exercises in the lesson. Save all portfolio assignments in separate Rmd files! Please create a separate RStudio project to complete all the portfolio assignments. The collection of all the portfolio assignments will form the main part of your portfolio for this course. The portfolio is also the exam for this course. **You will need to pass all portfolio assignments in order to pass the course!**. See \@ref(portfolioexam) for more info. 

As your work on the projecticum is probably your first real data science / bioinformatics project, your portfolio is the logical place to display it. Therefore, the work you do for the projecticum will also be part of your potfolio. However, the projecticum is only graded for the projecticum. 

Please also note that this is a 5 EC course, so count on about 140 hours of work in total. Part of this workload will be spread over the semester, to work on your portfolio. But we scheduled these lessons to ensure that you have most of the first 3 weeks in this semester available to finish the lessons in workflows. Use this time to you advantage! You will need the skills from this course within the projecticum. 


## failing or passing the course

This course is about the workflows that are available to adopt good practices in data science for biology. This is a field in which you rarely work alone. Participating and contributing to a data science community is an important skill to practice! Active participation is therefore conditional for getting a grade on your portfolio. 

Your final exam, as mentioned is your portfolio. After passing the course, you can convert this portfolio into your own personal digital CV.

