# Lesson 4.0 - Setting up a bookdown project and publishing it online as course portfolio {#bookdownportfolio}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Lesson aim
After this lesson you will be able to

 1. Setup github pages
 1. Create a bookdown project
 1. Render a bookdown project to a local website
 1. Add the rendered site to your github pages
 
## Github pages
Each account on github can be associated to one or multiple websites that are hosted on Github.com. To setup a website on Github (also called `github-pages` or `gh-pages`), we need to create a repository with a special name. For this course we will require you to upload results from the exercises and assignments results to you personal github pages. **This is a hard requirement for passing this course. If you have no or an empty portfolio, you cannot pass this course**

<div class="question">
##### Exercise 4.0

 1. Execute the steps explained [here](https://guides.github.com/features/pages/) to setup a github-pages repository called `workflows-portfolio`
 1. Send the url to your public portfolio address to the teachers by personal chat. 

</div>

## Bookdown
The `{bookdown}` R package is basically a collection of RMarkdown files, collated into a website with nice formatting and the possibility to cross reference and add citations and visualizations. The author of the bookdown is also the main author of `{knitr}`.    

## A simple bookdown example
To start with bookdown, there is a [good and free resource available](https://bookdown.org/yihui/bookdown/get-started.html). 

## Transform your current portfolio project to a bookdown site



## Render the book locally


## Hosting the bookdown project in your github pages

**IMPORTANT NOTE ON CONFIDENTIALITY**

<mark>**When hosting you portfolio on a public web address, please make sure that there is no confidential information visable in your project. Data that falls under a non-disclosure agreement for example from your projecticum may not be shared. Also, be sure not to publish any personal secrets such as passwords and tokens, inside a github repo or webpage.**</mark> 


